xfreerdp \
+clipboard \
+home-drive \
+unmap-buttons \
+async-channels \
+auto-reconnect \
-encryption \
/sound:rate:44100,channel:2 \
/kbd:0x00000409 \
/bpp:16 \
/audio-mode:0 \
/sound:sys:alsa \
/drive:media,/media \
/network:modem \
/cert-ignore \
/port:3389 \
/dynamic-resolution \
/compression-level:2 \
/v:8.8.8.8 \
/u:runner \
/p:iso.com \
/rfx \
/rfx-mode:video \
/codec-cache:rfx \
/gfx:rfx \
+gfx-progressive \
+gfx-small-cache \
+glyph-cache \
+bitmap-cache \
+offscreen-cache \
/proxy:socks5://127.0.0.1:1080 
